import { useSession, signIn, signOut } from "next-auth/react"
import Head from 'next/head';

const CreateProfile = () => {
  const { data: session } = useSession()
  if (session && session.user) {
    return (
      <>
        <Head>
          <title>Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Portfolio.png" />
        </Head>
        Signed in as {session.user.email} <br />
        <button onClick={() => signOut()}>Sign out</button>
      </>
    )
  }
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Portfolio.png" />
      </Head>
      Not signed in <br />
      <button onClick={() => signIn()}>Sign in to gain access</button>
    </>
  )
}

export default CreateProfile;
